"""Pacote de componentes de UI reutilizáveis."""
from .style_injector import inject_dashboard_style
from .kpi_cards import render_kpi_cards
from .charts import (
    apply_plotly_theme,
    make_bar_gasto_por_mes_unificado,
    make_bar_gasto_por_ano,
    make_donut_combustivel,
    make_donut_combustivel_valor,
    make_bar_consumo_tipo_mes,
    make_bar_consumo_tipo_mes_litros,
    make_bar_consumo_secretaria,
    make_bar_valor_vs_limite_secretaria,
    make_bar_litros_vs_limite_secretaria,
    make_ranking_consumo_secretaria,
    make_ranking_veiculos,
    make_treemap_postos,
    make_line_custo_medio_mes_combustivel,
    make_line_custo_medio_rl_combustivel,
    make_line_real_previsto_projecao,
    make_bar_comparativo_mensal_yoy,
    make_bar_comparativo_mensal_yoy_litros,
    make_line_sazonalidade_yoy,
    make_bar_consumo_combustivel,
)

__all__ = [
    "inject_dashboard_style",
    "render_kpi_cards",
    "apply_plotly_theme",
    "make_bar_gasto_por_mes_unificado",
    "make_bar_gasto_por_ano",
    "make_donut_combustivel",
    "make_donut_combustivel_valor",
    "make_bar_consumo_tipo_mes",
    "make_bar_consumo_tipo_mes_litros",
    "make_bar_consumo_secretaria",
    "make_bar_valor_vs_limite_secretaria",
    "make_bar_litros_vs_limite_secretaria",
    "make_ranking_consumo_secretaria",
    "make_ranking_veiculos",
    "make_treemap_postos",
    "make_line_custo_medio_mes_combustivel",
    "make_line_custo_medio_rl_combustivel",
    "make_line_real_previsto_projecao",
    "make_bar_comparativo_mensal_yoy",
    "make_bar_comparativo_mensal_yoy_litros",
    "make_line_sazonalidade_yoy",
    "make_bar_consumo_combustivel",
]
